<?php

namespace App\Models;

use App\Listeners\SendMailConfirmOrder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::updated(function ($order) {
            $columns = $order->getDirty();
            foreach ($columns as $column => $val){
                if ($column == 'status'){
                    dispatch(new SendMailConfirmOrder($order));
                }
            }
        });
    }
}
